{% set name = "here-map-widget-for-jupyter" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/here-map-widget-for-jupyter-{{ version }}.tar.gz
  sha256: e74f3790f3179ac4ada9439e4ce3a6a3beb1e4808a6dec9ef7e840d491163018

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging >=0.7.9
    - pip
    - python >=3.6
  run:
    - branca >=0.3.1,<0.5
    - ipywidgets >=7.6.0,<8
    - python >=3.6

test:
  imports:
    - here_map_widget
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/here-map-widget-for-jupyter/
  summary: A widget that enables you to use HERE Maps API for JavaScript in Jupyter Notebook.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sackh
