{% set name = "here-map-widget-for-jupyter" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/here-map-widget-for-jupyter-{{ version }}.tar.gz
  sha256: c86fa5bfd1c766c2877e31a6fe22e01cbece34375d87eb9c2887e9b9cbda9210

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging >=0.7.9
    - pip
    - python >=3.6
  run:
    - branca >=0.3.1,<0.5
    - ipywidgets >=7.6.0,<8
    - python >=3.6

test:
  imports:
    - here_map_widget
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/here-map-widget-for-jupyter/
  summary: A widget that enables you to use HERE Maps API for JavaScript in Jupyter Notebook.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sackh
